version: '2'
services:
  nginx:
      build: ./nginx
      volumes:
          - .:/usr/src/app
      links:
          - django
      ports:
          - "80:80"

  # This defines a service for the Django app
  django:
      build: .
      volumes:
          - .:/usr/src/app
      expose:
          - "8000"
      links:
          - postgres


  # This defines a service for the Postgres database
  postgres:
      image: postgres:9.3
      volumes:
        - data:/var/lib/postgresql/data/pgdata
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        PGDATA : /var/lib/postgresql/data/pgdata
volumes:
  data: {}
